name: Rodrigo Campos
favicon: null
layout_spectrum: 0.9004824592266232
typography_spectrum: 0.5340729106683284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3647317753639072
  lightness: 0.875464019132778
  saturation: 0.3414118627551943
  rhythmicContrast: 0.6489779157564044
purpose: []
